### ISSUE TITLE
'port xxx/tcp busy, please check'

### ISSUE THREAD

**Issue by DizKiller** [Jsitech/relayer#1]
Hello.. i am getting this error: (is it IDS?)

port 21/tcp busy, please check
port 25/tcp busy, please check
port 53/tcp busy, please check
port 80/tcp busy, please check
port 110/tcp busy, please check
port 139/tcp busy, please check
port 1433/tcp busy, please check
port 443/tcp busy, please check
port 587/tcp busy, please check
port 389/tcp busy, please check
port 445/tcp busy, please check
port 3141/tcp busy, please check
port 53/udp busy, please check
port 137/udp busy, please check
port 138/udp busy, please check
┌─[root@parrot]─[/home/monopwn/Other/relayer]

it got further 1 time i ran it before.
How would i approach this?

**Comment by Jsitech** [comment]
Run 
# fuser xxx/tcp

Responder must still be using the ports, just kill the process
